apiVersion: v1
kind: Service
metadata:
  name: quiz-svc
  namespace: default
spec:
  ports:
  - name: quiz
    port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: quiz
  sessionAffinity: None
  type: ClusterIP
