apiVersion: apps/v1
kind: Deployment
metadata:
  name: webserver
  namespace: default
spec:
  selector:
    matchLabels:
      app: webserver
  replicas: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: webserver
    spec:
      containers:
        - name: webserver
          image: asia.gcr.io/empirical-state-302503/webserver:latest
          imagePullPolicy: "Always"
          ports:
            - containerPort: 5000
