apiVersion: v1
kind: Service
metadata:
  name: list-word-svc
  namespace: default
spec:
  ports:
  - name: list-word
    port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: list-word
  sessionAffinity: None
  type: ClusterIP
