apiVersion: v1
kind: Service
metadata:
  name: haproxy-svc
spec:
  ports:
  - port: 30000
    protocol: TCP
    targetPort: 30000
    nodePort: 30000
  selector:
    app: haproxy
  type: LoadBalancer
