apiVersion: v1
kind: Service
metadata:
  name: add-new-word-svc
  namespace: default
spec:
  ports:
  - name: add-new-word
    port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: add-new-word
  sessionAffinity: None
  type: ClusterIP
